services:
  webapp:
    build: ./go
    environment:
      ISUCON_DB_HOST: isucon-s3
      ISUCON_DB_PORT: 3306
      ISUCON_DB_USER: isucon
      ISUCON_DB_PASSWORD: isucon
      ISUCON_DB_NAME: isuports
    network_mode: host
    volumes:
      - /home/isucon/isucon-practice-20231123-2/webapp/sql:/home/isucon/webapp/sql
      - /home/isucon/webapp/public.pem:/home/isucon/webapp/public.pem:ro
      - /home/isucon/tmp:/home/isucon/tmp
    init: true
